#ifndef VEHICLETERMINALUSERINTERFACE_GLOBAL_H
#define VEHICLETERMINALUSERINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VEHICLETERMINALUSERINTERFACE_LIB
# define VEHICLETERMINALUSERINTERFACE_EXPORT Q_DECL_EXPORT
#else
# define VEHICLETERMINALUSERINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // VEHICLETERMINALUSERINTERFACE_GLOBAL_H
