#ifndef VEHICLETERMINALCONTROLS_GLOBAL_H
#define VEHICLETERMINALCONTROLS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VEHICLETERMINALCONTROLS_LIB
# define VEHICLETERMINALCONTROLS_EXPORT Q_DECL_EXPORT
#else
# define VEHICLETERMINALCONTROLS_EXPORT Q_DECL_IMPORT
#endif

#endif // VEHICLETERMINALCONTROLS_GLOBAL_H
