#ifndef VEHICLETERMINALCOMMUNICATIONTOOLS_GLOBAL_H
#define VEHICLETERMINALCOMMUNICATIONTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VEHICLETERMINALCOMMUNICATIONTOOLS_LIB
# define VEHICLETERMINALCOMMUNICATIONTOOLS_EXPORT Q_DECL_EXPORT
#else
# define VEHICLETERMINALCOMMUNICATIONTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // VEHICLETERMINALCOMMUNICATIONTOOLS_GLOBAL_H
